export const GET_DOGS_REQUEST = 'GET_DOGS_REQUEST';
export const GET_DOGS_SUCCESS = 'GET_DOGS_SUCCESS';
export const GET_DOGS_FAILURE = 'GET_DOGS_FAILURE';

export const GET_DOG_DETAIL_REQUEST = 'GET_DOG_DETAIL_REQUEST';
export const GET_DOG_DETAIL_SUCCESS = 'GET_DOG_DETAIL_SUCCESS';
export const GET_DOG_DETAIL_FAILURE = 'GET_DOG_DETAIL_FAILURE';

export const POST_DOG_REQUEST = 'POST_DOG_REQUEST';
export const POST_DOG_SUCCESS = 'POST_DOG_SUCCESS';
export const POST_DOG_FAILURE = 'POST_DOG_FAILURE';

