   export const GET_TEMPERAMENTS_REQUEST = 'GET_TEMPERAMENTS_REQUEST'
   export const GET_TEMPERAMENTS_SUCCESS = 'GET_TEMPERAMENTS_SUCCESS'
   export const GET_TEMPERAMENTS_FAILURE = 'GET_TEMPERAMENTS_FAILURE'